CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Documents" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FileName" text NOT NULL,
    "FilePath" text NOT NULL,
    "UploadedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Documents" PRIMARY KEY ("Id")
);

CREATE TABLE "Projects" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "ImageUrl" text,
    "GithubUrl" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Projects" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250808012138_InitialCreate', '8.0.19');

COMMIT;

START TRANSACTION;

ALTER TABLE "Documents" DROP COLUMN "FilePath";

ALTER TABLE "Documents" ADD "FileData" bytea NOT NULL DEFAULT BYTEA E'\\x';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250808190103_UpdateDocumentToUseFileData', '8.0.19');

COMMIT;

START TRANSACTION;

ALTER TABLE "Documents" ADD "ContentType" text;

ALTER TABLE "Documents" ADD "Size" bigint;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250809164418_AddContentTypeAndSizeToDocuments', '8.0.19');

COMMIT;

START TRANSACTION;

CREATE TABLE "ContactMessages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "Message" text NOT NULL,
    "VerificationToken" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "Verified" boolean NOT NULL,
    "ClientIp" text,
    "UserAgent" text,
    CONSTRAINT "PK_ContactMessages" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250809184740_AddContactMessages', '8.0.19');

COMMIT;

START TRANSACTION;

DROP TABLE "ContactMessages";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250809202228_DropContactMessages', '8.0.19');

COMMIT;

START TRANSACTION;

CREATE TABLE "SiteProfiles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FullName" character varying(120) NOT NULL,
    "Tagline" character varying(240) NOT NULL,
    "About" text[] NOT NULL,
    "Github" character varying(200) NOT NULL,
    "LinkedIn" character varying(200) NOT NULL,
    "Instagram" character varying(200) NOT NULL,
    "Email" character varying(200) NOT NULL,
    CONSTRAINT "PK_SiteProfiles" PRIMARY KEY ("Id")
);

INSERT INTO "SiteProfiles" ("Id", "About", "Email", "FullName", "Github", "Instagram", "LinkedIn", "Tagline")
VALUES (1, ARRAY['Hakkımda 1','Hakkımda 2']::text[], 'mail@ornek.com', 'Ad Soyad', 'https://github.com/kullaniciadi', 'https://instagram.com/kullaniciadi', 'https://linkedin.com/in/kullaniciadi', 'Kısa açıklama');

SELECT setval(
    pg_get_serial_sequence('"SiteProfiles"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "SiteProfiles") + 1,
        nextval(pg_get_serial_sequence('"SiteProfiles"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250810191322_AddSiteProfile', '8.0.19');

COMMIT;

